spring:
  config:
    import: optional:file:.env[.properties]
  liquibase:
    change-log: db/changelog/master.xml
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
bot:
  token: ${BOT_TOKEN}
  service-accounts: []
